name: GCMS-CI

on:
  pull_request:
    branches:
      - 'fix/**'
      - 'feature/**'
      - 'releases/**'
    types: [opened, reopened]

jobs:
  GCMS-CI:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn' 

    - run: yarn install --frozen-lockfile
    - run: yarn test
    - run: yarn build
  
    - name: Success notification to discord
      uses: sarisia/actions-status-discord@v1.11.0
      if: ${{ success() }}
      with:
        webhook: ${{ secrets.WEBHOOK }}
        title: "GCMS CI successfully"
        description: "CI success"
        content: "success!!!"
        username: GCMS CI bot
        url: "https://github.com/GSM-MSG/GCMS-FrontEnd-V2"
        color: 4CAF50
  
    - name: Failure notification to discord
      uses: sarisia/actions-status-discord@v1.11.0
      if: ${{ failure() }}
      with:
        webhook: ${{ secrets.WEBHOOK }}
        title: "GCMS CI failed"
        description: "CI failed"
        content: "ㅆㅂ..."
        username: GCMS CI bot
        url: "https://github.com/GSM-MSG/GCMS-FrontEnd-V2"
        color: e74c3c
      
